# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "sisr_helpdesk",
        "version" : "0.1",
        "author" : "Tiny",
        "website" : "http://openerp.com",
        "category" : "Unknown",
        "description": """  """,
        "depends" : ['base', 'mail'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "update_xml" : ['sisr_helpdesk_view.xml','security/res.groups.xml','security/ir.model.access.csv','workflow/sisrhelpdesk_Workflow.xml','security/ir.rule.xml','incidencia_codigo_sequence.xml','data/area_incidencia.xml','data/tipo_incidencia.xml'],
        "installable": True
}
